wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1670274986.629026
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.5
      8:
      - 2
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 5
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
